# -*- coding: utf-8 -*-
"""Q1_NARRA_FA1_NERPIOL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LtLQTqZGyIpkHCKW2pLiLFVgQyy5TYan
"""

import math
int(input("x1"))
int(input("x2"))
int(input("y1"))
int(input("y2"))

d = pow((x2 - x1), 2) + pow((y2 - y1 ), 2)
print(math.sqrt(d))


#When using a library it is more practical because it is easier and automatic. You can also see where you got it wrong to help you.